kind = "web"
previewPath = "/"
title = "Infomist"
version = "1.0.0"
id = "artifacts/infomist-web"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21468

[services.development]
run = "pnpm --filter @workspace/infomist-web run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/infomist-web", "run", "build" ]
serve = "static"
publicDir = "artifacts/infomist-web/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21468"
BASE_PATH = "/"
